version: '3.0'

services:
    django:
        build: ./requirements/django
        container_name: django
        restart: on-failure
        expose:
            - '8000'
        volumes:
            - ./requirements/django/src:/srv/ft_transcendence_backend/www/src
        networks:
            - eralonso
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        restart: on-failure
        ports:
            - '443:443'
        volumes:
            - ./requirements/nginx/html:/var/www/html
        networks:
            - eralonso
    postgres_db:
        image: postgres:16-alpine
        container_name: postgres_db
        restart: on-failure
        expose:
            - '5432'
        volumes:
            - ./postgres_db:/var/lib/postgresql/data
        environment:

        networks:
            - eralonso

networks:
    eralonso:
        name: eralonso
        driver: bridge
