version: '3.0'

services:
    django:
        build: ./requirements/django
        container_name: django
        restart: on-failure
        expose:
            - '8000'
        volumes:
            - /Users/eralonso/Documents/github/learningDjango/requirements/django/src:/srv/ft_transcendence_backend/www/src
        networks:
            - eralonso
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        restart: on-failure
        ports:
            - '443:443'
        networks:
            - eralonso
    #TODO: Add postgreSQL
    #postgres_db:
    #   image: 

networks:
    eralonso:
        name: eralonso
        driver: bridge
