version: '3.0'

services:
    django:
        build: ./requirements/django
        container_name: django
        restart: on-failure
        expose:
            - '8000'
        #ports:
        #    - '8000:8000'
        volumes:
            - /Users/eralonso/Documents/github/learningDjango/requirements/django:/srv/ft_transcendence_backend/www
        networks:
            - eralonso
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        restart: on-failure
        ports:
            - '1010:1010'
        networks:
            - eralonso
    #TODO: Add postgreSQL
    #postgres_db:
    #   image: 

networks:
    eralonso:
        driver: bridge
