# Generated by Django 4.1.4 on 2024-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelname',
            name='my_field_name',
            field=models.CharField(help_text='Enter field Documentation', max_length=20, verbose_name='patata'),
        ),
    ]
